apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-demo
  # replicaSet labels
  labels: 
    project: roboshop
    purpose: deployment-demo
    component: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      project: roboshop
      purpose: deployment-demo
      component: frontend
  # pod definition
  template:
    metadata:
      labels:
        project: roboshop
        purpose: deployment-demo
        component: frontend
    spec:
      containers:
        - name: frontend
          image: nginx:1.24